### ISSUE TITLE
Do not use pointer at active sidebar nav item

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/owncloud-design-system#693] opened 2020-03-26 13:35 UTC
Since Vue doesn't allow navigation to current route, let's not use pointer there.

**Comment by pascalwengerter** [comment] 2021-04-08 14:55
Can't reproduce, when hovering over the active nav item in web/oCIS it's not a clickable link/mouse is not displayed as pointer

**Comment by pascalwengerter** [comment] 2021-06-02 16:25
Closing this as fixed, can't reproduce neither in ODS nor web

**Closed by pascalwengerter** 2021-06-02 16:25 UTC
